### ISSUE TITLE
Cannot import 'array_record_module'

### ISSUE THREAD

**Issue by TastyCake** [google/array_record#47]
So I am trying to use the mediapipe-model-maker which needs the tensorflow_datasets package and this package uses this package (array-record) and I am getting this error while running the code:
Traceback (most recent call last):
  File "C:\Users\sinit\AndroidStudioProjects\HandGestureLTA\modelPython\model.py", line 8, in <module>
    from mediapipe_model_maker import gesture_recognizer as gr
  File "C:\venv\lib\site-packages\mediapipe_model_maker\__init__.py", line 17, in <module>
    from mediapipe_model_maker.python.vision import image_classifier
  File "C:\venv\lib\site-packages\mediapipe_model_maker\python\vision\image_classifier\__init__.py", line 16, in <module>
    from mediapipe_model_maker.python.vision.image_classifier import dataset
  File "C:\venv\lib\site-packages\mediapipe_model_maker\python\vision\image_classifier\dataset.py", line 21, in <module>
    import tensorflow_datasets as tfds
  File "C:\venv\lib\site-packages\tensorflow_datasets\__init__.py", line 43, in <module>
    import tensorflow_datasets.core.logging as _tfds_logging
  File "C:\venv\lib\site-packages\tensorflow_datasets\core\__init__.py", line 22, in <module>
    from tensorflow_datasets.core import community
  File "C:\venv\lib\site-packages\tensorflow_datasets\core\community\__init__.py", line 18, in <module>
    from tensorflow_datasets.core.community.huggingface_wrapper import mock_builtin_to_use_gfile
  File "C:\venv\lib\site-packages\tensorflow_datasets\core\community\huggingface_wrapper.py", line 31, in <module>
    from tensorflow_datasets.core import dataset_builder
  File "C:\venv\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 34, in <module>
    from tensorflow_datasets.core import dataset_info
  File "C:\venv\lib\site-packages\tensorflow_datasets\core\dataset_info.py", line 47, in <module>
    from tensorflow_datasets.core import file_adapters
  File "C:\venv\lib\site-packages\tensorflow_datasets\core\file_adapters.py", line 29, in <module>
    from array_record.python import array_record_module
ImportError: cannot import name 'array_record_module' from 'array_record.python' (C:\venv\lib\site-packages\array_record\python\__init__.py)

**Comment by Opium1715** [comment]
I met the same problem when I try to use tensorflow_datasets.
Here is my way to deal with this:
    Downgrade the tensorflow_datasets to 4.8.3.
I hope it could help you.

**Comment by Opium1715** [comment]
> So I am trying to use the mediapipe-model-maker which needs the tensorflow_datasets package and this package uses this package (array-record) and I am getting this error while running the code: Traceback (most recent call last): File "C:\venv\lib\site-packages\mediapipe_model_maker__init__.py", line 17, in from mediapipe_model_maker.python.vision import image_classifier File "C:\venv\lib\site-packages\mediapipe_model_maker\python\vision\image_classifier__init__.py", line 16, in from mediapipe_model_maker.python.vision.image_classifier import dataset File "C:\venv\lib\site-packages\mediapipe_model_maker\python\vision\image_classifier\dataset.py", line 21, in import tensorflow_datasets as tfds File "C:\venv\lib\site-packages\tensorflow_datasets__init__.py", line 43, in import tensorflow_datasets.core.logging as _tfds_logging File "C:\venv\lib\site-packages\tensorflow_datasets\core__init__.py", line 22, in from tensorflow_datasets.core import community File "C:\venv\lib\site-packages\tensorflow_datasets\core\community__init__.py", line 18, in from tensorflow_datasets.core.community.huggingface_wrapper import mock_builtin_to_use_gfile File "C:\venv\lib\site-packages\tensorflow_datasets\core\community\huggingface_wrapper.py", line 31, in from tensorflow_datasets.core import dataset_builder File "C:\venv\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 34, in from tensorflow_datasets.core import dataset_info File "C:\venv\lib\site-packages\tensorflow_datasets\core\dataset_info.py", line 47, in from tensorflow_datasets.core import file_adapters File "C:\venv\lib\site-packages\tensorflow_datasets\core\file_adapters.py", line 29, in from array_record.python import array_record_module ImportError: cannot import name 'array_record_module' from 'array_record.python' (C:\venv\lib\site-packages\array_record\python__init__.py)
I met the same issue when I try to use tensorflow_datasets.
You can try to downgrade tensorflow_datasets to 4.8.3.
I hope it could help you.

**Comment by Opium1715** [comment]
> So I am trying to use the mediapipe-model-maker which needs the tensorflow_datasets package and this package uses this package (array-record) and I am getting this error while running the code: Traceback (most recent call last): File "C:\venv\lib\site-packages\mediapipe_model_maker__init__.py", line 17, in from mediapipe_model_maker.python.vision import image_classifier File "C:\venv\lib\site-packages\mediapipe_model_maker\python\vision\image_classifier__init__.py", line 16, in from mediapipe_model_maker.python.vision.image_classifier import dataset File "C:\venv\lib\site-packages\mediapipe_model_maker\python\vision\image_classifier\dataset.py", line 21, in import tensorflow_datasets as tfds File "C:\venv\lib\site-packages\tensorflow_datasets__init__.py", line 43, in import tensorflow_datasets.core.logging as _tfds_logging File "C:\venv\lib\site-packages\tensorflow_datasets\core__init__.py", line 22, in from tensorflow_datasets.core import community File "C:\venv\lib\site-packages\tensorflow_datasets\core\community__init__.py", line 18, in from tensorflow_datasets.core.community.huggingface_wrapper import mock_builtin_to_use_gfile File "C:\venv\lib\site-packages\tensorflow_datasets\core\community\huggingface_wrapper.py", line 31, in from tensorflow_datasets.core import dataset_builder File "C:\venv\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 34, in from tensorflow_datasets.core import dataset_info File "C:\venv\lib\site-packages\tensorflow_datasets\core\dataset_info.py", line 47, in from tensorflow_datasets.core import file_adapters File "C:\venv\lib\site-packages\tensorflow_datasets\core\file_adapters.py", line 29, in from array_record.python import array_record_module ImportError: cannot import name 'array_record_module' from 'array_record.python' (C:\venv\lib\site-packages\array_record\python__init__.py)

I met the same issue when I try to use tensorflow_datasets.
You can try to downgrade tensorflow_datasets to 4.8.3.
I hope it could help you.
